// Encrypted travel blog. Everything in js/traveldata.js (generated by
// tools/encrypt_travel.js) is real AES-256-GCM ciphertext keyed by
// PBKDF2(answer) - there is no plaintext anywhere in this file or that one.
// Getting the answer right derives the real key and the browser's own
// WebCrypto decrypts everything client-side; getting it wrong just fails
// the auth tag check, same as any other AES-GCM decrypt.
(function () {
  var root = document.getElementById("travel-root");
  if (!root) return;

  var entries = window.TRAVEL_ENTRIES || [];
  var saltB64 = window.TRAVEL_SALT;
  var iterations = window.TRAVEL_ITERATIONS || 250000;

  var plaintextCache = null; // filled in once the answer checks out

  function t(key) {
    return window.t ? window.t(key) : key;
  }

  function lang() {
    return window.getLang ? window.getLang() : "en";
  }

  function normalizeAnswer(s) {
    return s
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .trim()
      .replace(/\s+/g, " ");
  }

  function b64ToBytes(b64) {
    var bin = atob(b64);
    var bytes = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes;
  }

  function deriveKey(answer) {
    var enc = new TextEncoder();
    return crypto.subtle
      .importKey("raw", enc.encode(normalizeAnswer(answer)), "PBKDF2", false, ["deriveKey"])
      .then(function (baseKey) {
        return crypto.subtle.deriveKey(
          { name: "PBKDF2", salt: b64ToBytes(saltB64), iterations: iterations, hash: "SHA-256" },
          baseKey,
          { name: "AES-GCM", length: 256 },
          false,
          ["decrypt"]
        );
      });
  }

  function decryptBuf(key, field) {
    var iv = b64ToBytes(field.iv);
    var data = b64ToBytes(field.data);
    return crypto.subtle.decrypt({ name: "AES-GCM", iv: iv }, key, data);
  }

  function decryptText(key, field) {
    return decryptBuf(key, field).then(function (buf) {
      return new TextDecoder().decode(buf);
    });
  }

  function decryptImage(key, field) {
    return decryptBuf(key, field).then(function (buf) {
      return URL.createObjectURL(new Blob([buf], { type: field.mime }));
    });
  }

  // A block is either { type: "text", body: {en,es} } or { type: "image",
  // date? } - order in the array is the author's own order, interleaving
  // text and photos however they liked, so decrypting one preserves its
  // shape instead of collapsing back into separate arrays.
  function decryptBlock(key, block) {
    if (block.type === "image") {
      return Promise.all([
        decryptImage(key, block),
        block.date ? decryptText(key, block.date) : Promise.resolve(null),
      ]).then(function (r) {
        return { type: "image", url: r[0], date: r[1] };
      });
    }
    return Promise.all([
      decryptText(key, block.body.en),
      decryptText(key, block.body.es),
    ]).then(function (r) {
      return { type: "text", body: { en: r[0], es: r[1] } };
    });
  }

  function decryptAll(key) {
    return Promise.all(
      entries.map(function (entry) {
        return Promise.all([
          decryptText(key, entry.title.en),
          decryptText(key, entry.title.es),
          decryptText(key, entry.location.en),
          decryptText(key, entry.location.es),
          decryptText(key, entry.date),
          Promise.all((entry.blocks || []).map(function (b) { return decryptBlock(key, b); })),
        ]).then(function (r) {
          return {
            id: entry.id,
            title: { en: r[0], es: r[1] },
            location: { en: r[2], es: r[3] },
            date: r[4],
            blocks: r[5],
          };
        });
      })
    ).then(function (decrypted) {
      // Newest trip first. Dates are plain "YYYY-MM-DD" strings, which
      // already sort correctly as plain text.
      return decrypted.slice().sort(function (a, b) {
        return a.date < b.date ? 1 : a.date > b.date ? -1 : 0;
      });
    });
  }

  // ---- "looks encrypted" teaser, shown before unlock -----------------

  function renderLocked() {
    var cards = entries
      .map(function (entry) {
        var firstText = (entry.blocks || []).filter(function (b) { return b.type === "text"; })[0];
        var previewCipher = firstText ? firstText.body.en.data.slice(0, 120) : "";
        return (
          '<div class="travel-card travel-card-locked">' +
          '<div class="travel-cipher-block">' + entry.title.en.data + "</div>" +
          '<div class="travel-cipher-block travel-cipher-dim">' + previewCipher + "</div>" +
          "</div>"
        );
      })
      .join("");
    var list = document.getElementById("travel-locked-list");
    if (list) list.innerHTML = cards;
  }

  // ---- text scramble-reveal animation ---------------------------------

  var SCRAMBLE_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789#%&*+=/\\";

  function scrambleReveal(el, finalText, durationMs) {
    var start = null;
    function frame(ts) {
      if (start === null) start = ts;
      var elapsed = ts - start;
      var progress = Math.min(1, elapsed / durationMs);
      var settledCount = Math.floor(progress * finalText.length);
      var out = "";
      for (var i = 0; i < finalText.length; i++) {
        if (i < settledCount || finalText[i] === " ") {
          out += finalText[i];
        } else {
          out += SCRAMBLE_CHARS[Math.floor(Math.random() * SCRAMBLE_CHARS.length)];
        }
      }
      el.textContent = out;
      if (progress < 1) requestAnimationFrame(frame);
      else el.textContent = finalText;
    }
    requestAnimationFrame(frame);
  }

  // ---- image tile-shuffle reveal ---------------------------------------

  function revealImageTiles(canvas, imgUrl, cols, rows, durationMs) {
    var img = new Image();
    img.onload = function () {
      var displayW = Math.min(img.naturalWidth, canvas.parentElement.clientWidth || 480);
      var displayH = Math.round((displayW / img.naturalWidth) * img.naturalHeight);
      canvas.width = displayW;
      canvas.height = displayH;
      var ctx = canvas.getContext("2d");

      var tileW = displayW / cols;
      var tileH = displayH / rows;
      var tiles = [];
      for (var r = 0; r < rows; r++) {
        for (var c = 0; c < cols; c++) tiles.push({ r: r, c: c });
      }
      var shuffled = tiles.slice();
      for (var i = shuffled.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var tmp = shuffled[i]; shuffled[i] = shuffled[j]; shuffled[j] = tmp;
      }

      var start = null;
      function drawFrame(ts) {
        if (start === null) start = ts;
        var elapsed = ts - start;
        var progress = Math.min(1, elapsed / durationMs);
        var eased = 1 - Math.pow(1 - progress, 3);

        ctx.clearRect(0, 0, displayW, displayH);
        for (var k = 0; k < tiles.length; k++) {
          var target = tiles[k];
          var from = shuffled[k];
          var curC = from.c + (target.c - from.c) * eased;
          var curR = from.r + (target.r - from.r) * eased;
          ctx.drawImage(
            img,
            (target.c * tileW / displayW) * img.naturalWidth, (target.r * tileH / displayH) * img.naturalHeight,
            tileW / displayW * img.naturalWidth, tileH / displayH * img.naturalHeight,
            curC * tileW, curR * tileH, tileW + 0.5, tileH + 0.5
          );
        }
        if (progress < 1) requestAnimationFrame(drawFrame);
      }
      requestAnimationFrame(drawFrame);
    };
    img.src = imgUrl;
  }

  // ---- rendering unlocked content ---------------------------------------
  // Like My Projects: a grid of preview cards (one per trip, newest first,
  // just a thumbnail + title) rather than dumping every trip's full text and
  // photos onto the page at once. "Read more" opens that one trip's full
  // write-up in its own window (#travel-entry-root), same as a project's
  // "To know more" opens its blog post.

  var openEntryId = null; // which trip (if any) is showing in the entry window

  function firstImageBlock(entry) {
    for (var i = 0; i < entry.blocks.length; i++) {
      if (entry.blocks[i].type === "image") return { block: entry.blocks[i], idx: i };
    }
    return null;
  }

  function renderTripGrid() {
    var L = lang();
    var marqueeHtml =
      '<div class="travel-marquee"><span>' + escapeAttr(t("travel.marquee")) + "</span></div>";
    var cardsHtml = plaintextCache
      .map(function (entry) {
        var thumb = firstImageBlock(entry);
        var thumbHtml = thumb
          ? '<div class="travel-image-wrap"><canvas class="travel-canvas travel-preview-thumb" data-entry="' + entry.id + '" data-idx="' + thumb.idx + '"></canvas></div>'
          : "";
        return (
          '<div class="travel-preview-card">' +
          thumbHtml +
          '<h2 class="travel-scramble" data-final="' + escapeAttr(entry.title[L]) + '"></h2>' +
          '<p class="travel-meta"><span class="travel-scramble" data-final="' + escapeAttr(entry.location[L]) + '"></span> · ' + escapeAttr(entry.date) + "</p>" +
          '<button type="button" class="btn98 travel-readmore" data-id="' + escapeAttr(entry.id) + '">' + escapeAttr(t("travel.readMore")) + "</button>" +
          "</div>"
        );
      })
      .join("");
    var content = document.getElementById("travel-content");
    content.innerHTML = marqueeHtml + '<div class="travel-preview-grid">' + cardsHtml + "</div>";

    content.querySelectorAll(".travel-scramble").forEach(function (el) {
      scrambleReveal(el, el.getAttribute("data-final"), 500);
    });
    plaintextCache.forEach(function (entry) {
      var thumb = firstImageBlock(entry);
      if (!thumb) return;
      var canvas = content.querySelector('canvas[data-entry="' + entry.id + '"][data-idx="' + thumb.idx + '"]');
      if (canvas) revealImageTiles(canvas, thumb.block.url, 4, 3, 700);
    });
    content.querySelectorAll(".travel-readmore").forEach(function (btn) {
      btn.addEventListener("click", function () {
        if (window.SFX) window.SFX.click();
        openTripEntry(btn.getAttribute("data-id"));
      });
    });
  }

  function renderEntry(entry) {
    var L = lang();
    var root = document.getElementById("travel-entry-root");
    if (!root) return;
    var titleEl = document.getElementById("travel-entry-title");
    if (titleEl) titleEl.textContent = entry.title[L] + " — " + t("win.travel");

    var blocksHtml = entry.blocks
      .map(function (block, idx) {
        if (block.type === "image") {
          var dateHtml = block.date ? '<p class="travel-image-date">' + escapeAttr(block.date) + "</p>" : "";
          return (
            '<div class="travel-image-wrap">' +
            '<canvas class="travel-canvas" data-idx="' + idx + '"></canvas>' +
            dateHtml +
            "</div>"
          );
        }
        return '<p class="travel-scramble" data-final="' + escapeAttr(block.body[L]) + '"></p>';
      })
      .join("");
    root.innerHTML =
      '<div class="travel-content">' +
      '<article class="travel-card">' +
      '<h2 class="travel-scramble" data-final="' + escapeAttr(entry.title[L]) + '"></h2>' +
      '<p class="travel-meta"><span class="travel-scramble" data-final="' + escapeAttr(entry.location[L]) + '"></span> · ' + escapeAttr(entry.date) + "</p>" +
      blocksHtml +
      "</article>" +
      "</div>";

    root.querySelectorAll(".travel-scramble").forEach(function (el) {
      scrambleReveal(el, el.getAttribute("data-final"), 500);
    });
    entry.blocks.forEach(function (block, idx) {
      if (block.type !== "image") return;
      var canvas = root.querySelector('canvas[data-idx="' + idx + '"]');
      if (canvas) revealImageTiles(canvas, block.url, 6, 4, 900);
    });
  }

  function openTripEntry(id) {
    var entry = plaintextCache && plaintextCache.filter(function (e) { return e.id === id; })[0];
    if (!entry) return;
    openEntryId = id;
    renderEntry(entry);
    if (window.openAppWindow) window.openAppWindow("travel-entry");
  }

  function escapeAttr(str) {
    var div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML.replace(/"/g, "&quot;");
  }

  // ---- lock screen wiring -----------------------------------------------

  var form = document.getElementById("travel-unlock-form");
  var input = document.getElementById("travel-answer");
  var errorEl = document.getElementById("travel-error");
  var submitBtn = document.getElementById("travel-submit");
  var lockSection = document.getElementById("travel-lock");
  var contentSection = document.getElementById("travel-content");

  function showError(msg) {
    errorEl.textContent = msg;
    lockSection.classList.remove("shake");
    void lockSection.offsetWidth; // restart animation
    lockSection.classList.add("shake");
  }

  function handleSubmit(e) {
    e.preventDefault();
    if (!entries.length) return;
    var answer = input.value;
    if (!answer) return;
    submitBtn.disabled = true;
    submitBtn.textContent = t("travel.checking");
    errorEl.textContent = "";

    deriveKey(answer)
      .then(function (key) {
        return decryptAll(key);
      })
      .then(function (decrypted) {
        plaintextCache = decrypted;
        lockSection.hidden = true;
        contentSection.hidden = false;
        renderTripGrid();
      })
      .catch(function () {
        showError(t("travel.wrong"));
        input.value = "";
        input.focus();
      })
      .finally(function () {
        submitBtn.disabled = false;
        submitBtn.textContent = t("travel.unlock");
      });
  }

  if (form) form.addEventListener("submit", handleSubmit);

  document.addEventListener("langchange", function () {
    if (!plaintextCache) { renderLocked(); return; }
    renderTripGrid();
    if (openEntryId) {
      var entry = plaintextCache.filter(function (e) { return e.id === openEntryId; })[0];
      if (entry) renderEntry(entry);
    }
  });

  renderLocked();
})();
